export default {
  getNewsRequest: 'GET_NEWS_REQUEST',
  getNewsSuccess: 'GET_NEWS_SUCCESS',
  getNewsFailure: 'GET_NEWS_FAILURE',
  loginUserRequest: 'LOGIN_USER_REQUEST',
  loginUserSuccess: 'LOGIN_USER_SUCCESS',
  loginUserFailure: 'LOGIN_USER_FAILURE',
  getAuthorsRequest: 'GET_AUTHORS_REQUEST',
  getAuthorsSuccess: 'GET_AUTHORS_SUCCESS',
  getAuthorsFailure: 'GET_AUTHORS_FAILURE',
  postAuthorRequest: 'POST_AUTHOR_REQUEST',
  postAuthorSuccess: 'POST_AUTHOR_SUCCESS',
  postAuthorFailure: 'POST_AUTHOR_FAILURE',
  deleteNewsRequest: 'DELETE_NEWS_REQUEST',
  deleteNewsSuccess: 'DELETE_NEWS_SUCCESS',
  deleteNewsFailure: 'DELETE_NEWS_FAILURE',
  addNewsRequest: 'ADD_NEWS_REQUEST',
  addNewsSuccess: 'ADD_NEWS_SUCCESS',
  addNewsFailure: 'ADD_NEWS_FAILURE',
  updateNewsRequest: 'UPDATE_NEWS_REQUEST',
  updateNewsSuccess: 'UPDATE_NEWS_SUCCESS',
  updateNewsFailure: 'UPDATE_NEWS_FAILURE',
  selectNews: 'SELECT_NEWS',
  clearSelectNews: 'CLEAR_SELECT_NEWS'
};
